version: "3.6"
services:
  db:
    image: postgres:14
    container_name: payment-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - '54324:5432'
